//
//  tst.swift
//  GetCoupon
//
//  Created by Nikita Konashenko on 24.11.2019.
//  Copyright © 2019 Nikita Konashenko. All rights reserved.
//


import UIKit

//struct Promoсode: Decodable {
//
//    let name: String //= "Some Coupon"
//    let estimatedDate: String?
//    let description: String? //= "Short decription"
//    let websiteLink: String //= "Link"
//    let isHot: Bool //= false
//}
//
//struct Shop: Decodable {
//
//    let name: String //= "Shop Name"
//    let description: String? //= "Full description"
//    let shortDescription: String //= "Short description"
//
//    let websiteLink: String //= "www.ShopName.com"
//
//    let imageLink: String? //= ".../fullImage"
//    let previewImageLink: String? //= ".../previewImage"
//
//    let promocodes: [Promoсode] //= []
//}
//
//struct ShopCategory: Decodable {
//
//    let name: String //= "Category Name"
//
//    let tags: [String] //= []
//
//    let shops: [Shop] //= []
//}
//
//struct Model {
//
//    let categories: [ShopCategory] = []
//}



//// FOR TESTS
//func generateCollections() {
//        let _collections = [
//            SectionData(sectionTitle: "HOT 🔥",
//                            cells: [CellData(image: UIImage(named: "Delivery"),
//                                             title: "Delivery Club",
//                                             subtitle: "Save your 35%"),
//                                    CellData(image: UIImage(named: "Yandex"),
//                                             title: "Yandex Food",
//                                             subtitle: "Save your 15%"),
//                                    CellData(image: UIImage(named: "WaterPark"),
//                                             title: "Water Park Caribbean",
//                                             subtitle: "Your have personal coupon"),
//                                    CellData(image: UIImage(named: "Ozon"),
//                                             title: "Ozon",
//                                             subtitle: "Save your 25%"),
//                                    CellData(image: UIImage(named: "AliExpress"),
//                                             title: "AliExpress",
//                                             subtitle: "Save your 60%"),
//                                    CellData(image: UIImage(named: "ASOS"),
//                                             title: "ASOS",
//                                             subtitle: "Your have personal coupon"),
//                                    CellData(image: UIImage(named: "Amazon"),
//                                             title: "Amazon",
//                                             subtitle: "Save your 30%"),
//                                    CellData(image: UIImage(named: "Apple"),
//                                             title: "Apple",
//                                             subtitle: "Special inventational")]),
//            SectionData(sectionTitle: "Food",
//                            cells: [CellData(image: UIImage(named: "KFC"),
//                                             title: "KFC",
//                                             subtitle: "Two for one price"),
//                                    CellData(image: UIImage(named: "McDonald's"),
//                                             title: "McDonald's",
//                                             subtitle: "New menu"),
//                                    CellData(image: UIImage(named: "Yakitoria"),
//                                             title: "Yakitoria",
//                                             subtitle: "Save your 10%"),
//                                    CellData(image: UIImage(named: "KFC"),
//                                             title: "KFC",
//                                             subtitle: "Two for one price"),
//                                    CellData(image: UIImage(named: "McDonald's"),
//                                             title: "McDonald's",
//                                             subtitle: "New menu"),
//                                    CellData(image: UIImage(named: "Yakitoria"),
//                                             title: "Yakitoria",
//                                             subtitle: "Save your 10%")]),
//            SectionData(sectionTitle: "Other",
//                            cells: [CellData(image: UIImage(named: "Amazon"),
//                                             title: "Amazon",
//                                             subtitle: "Save your 30%"),
//                                    CellData(image: UIImage(named: "Apple"),
//                                             title: "Apple",
//                                             subtitle: "Special inventational"),
//                                    CellData(image: UIImage(named: "AliExpress"),
//                                             title: "AliExpress",
//                                             subtitle: "Save your 60%"),
//                                    CellData(image: UIImage(named: "ASOS"),
//                                             title: "ASOS",
//                                             subtitle: "Your have personal coupon")])
//        ]
//}

let promocodes: [PromocodeData] = [
    PromocodeData(coupon: "COUPON30",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 3),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 7),
                  description: "Save your 30% when spent more than 5000",
                  isHot: false),
    PromocodeData(coupon: "COUPON20",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 2),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 6),
                  description: "Amazing discounts up to 20% on sale!",
                  isHot: false),
    PromocodeData(coupon: "COUPON10",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 1),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 5),
                  description: "Save your 10% when spent more than 1000",
                  isHot: false),
    PromocodeData(coupon: "COUPON40",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 3),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 4),
                  description: "The promotional code for an additional discount of 40%.",
                  isHot: false),
    PromocodeData(coupon: "COUPON50",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 3),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 3),
                  description: "The promotional code for an additional discount of 50%.",
                  isHot: false),
    PromocodeData(coupon: "COUPON60",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 1),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 2),
                  description: "Amazing discounts up to 60% on sale!",
                  isHot: false),
    PromocodeData(coupon: "COUPON70",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 1),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 1),
                  description: "Save your 70% when spent more than 15000",
                  isHot: false),
    PromocodeData(coupon: "COUPON80",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 1),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 1),
                  description: "Amazing discounts up to 80% on sale!",
                  isHot: false),
    PromocodeData(coupon: "COUPON90",
                  addingDate: Date(timeIntervalSinceNow: -60 * 60 * 24 * 1),
                  estimatedDate: Date(timeIntervalSinceNow: 60 * 60 * 24 * 1),
                  description: "Amazing discounts up to 90% on sale!",
                  isHot: false)
]

let collections: [ShopCategoryData] = [
    ShopCategoryData(categoryName: "HOT 🔥",
                     shops: [ShopData(name: "Delivery Club",
                                      description: "Delivery of dairy, farm products, confectionery and ready meals (pizza, sushi, barbecue, etc.).", shortDescription: "Save your 35%",
                                      websiteLink: "https://www.delivery-club.ru",
                                      imageLink: "https://lisa.ru/wp-content/uploads/2016/12/wok-1024x537.jpg",
                                      previewImageLink: "https://sun9-65.userapi.com/c858136/v858136966/700ec/IBrWLeJ3jT0.jpg",
                                      placeholderColor: #colorLiteral(red: 0.6835173368, green: 0.8750453591, blue: 0.1662097871, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Yandex Food",
                                      description: "Order food from restaurants - fast delivery in 45 minutes.",
                                      shortDescription: "Save your 15%",
                                      websiteLink: "https://eda.yandex",
                                      imageLink: "https://avatars.mds.yandex.net/get-zen_doc/1857554/pub_5cff8dcfaac1d000ab158f45_5cff8e97f6fb2600b0ea3547/scale_1200",
                                      previewImageLink: "https://rusevik.ru/data/news/5a9971862127c.png",
                                      placeholderColor: #colorLiteral(red: 0.9722293019, green: 0.5698908567, blue: 0.003058324102, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Water Park Caribbean",
                                      description: "Water slides, open beaches, a bath complex, pools, game rooms, a fitness club ... and that's not all!",
                                      shortDescription: "Your have personal coupon",
                                      websiteLink: "https://karibiya.ru",
                                      imageLink: "https://pbs.twimg.com/media/D3PO52-W4AEOm0k.jpg",
                                      previewImageLink: "https://cdn.freelance.ru/img/portfolio/thumb/00/37/0D/3607966.png",
                                      placeholderColor: #colorLiteral(red: 0.998680532, green: 0.8855193257, blue: 0.002513965359, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Ozon",
                                      description: "OZON Online Store - Low Prices on Millions of Products! Electronics, clothing, cosmetics, books, pet supplies, products and more.",
                                      shortDescription: "Save your 25%",
                                      websiteLink: "https://www.ozon.ru",
                                      imageLink: "http://investorov.net/sites/default/files/news/755053760199460.jpg",
                                      previewImageLink: "http://www.chinasexq.com/report3/uploadfile/201901/20190131133205710.jpg",
                                      placeholderColor: #colorLiteral(red: 0.007939346135, green: 0.7317495346, blue: 0.9377294183, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "AliExpress",
                                      description: "Sale of cell phones, computers, electronics, clothing, household goods, leisure and sports. Quick Guide and Buyer Tips.",
                                      shortDescription: "Save your 60%",
                                      websiteLink: "https://ru.aliexpress.com",
                                      imageLink: "https://i.ytimg.com/vi/KJNQB0NT5CE/maxresdefault.jpg",
                                      previewImageLink: "https://krasnodarik.ru/novosti/photo/cf9552e8e3bec01637592240bef1c34c.jpg",
                                      placeholderColor: #colorLiteral(red: 0.8950105309, green: 0.1806768477, blue: 0.02160408907, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "ASOS",
                                      description: "Buy trendy clothes online at ASOS! A huge selection of stylish women's and men's clothing.",
                                      shortDescription: "Your have personal coupon",
                                      websiteLink: "https://www.asos.com/ru",
                                      imageLink: "https://www.glossy.co/wp-content/uploads/2016/09/AsosResponse2Big.jpg",
                                      previewImageLink: "https://besplatka.ua/aws/77/17/19/12/app/prodam-zhenskuyu-obuv-stok-asos-photo-771b.jpg",
                                      placeholderColor: #colorLiteral(red: 0.1174927279, green: 0.1178211495, blue: 0.1089733914, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Amazon",
                                      description: "Low prices at Amazon on digital cameras, MP3, sports, books, music, DVDs, video games, home & garden and much more.",
                                      shortDescription: "Save your 30%",
                                      websiteLink: "https://www.amazon.co.uk",
                                      imageLink: "https://pbs.twimg.com/media/DBnCaOaUQAAGqfB.jpg",
                                      previewImageLink: "https://pbs.twimg.com/media/EF3EY2uXkAAgujv.jpg",
                                      placeholderColor: #colorLiteral(red: 0.9790428281, green: 0.6623874307, blue: 0.07724457234, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Apple",
                                      description: "Check out Apple innovations. Choose and buy your iPhone, iPad, Apple Watch, Mac, and Apple TV.",
                                      shortDescription: "Special inventational",
                                      websiteLink: "https://www.apple.com",
                                      imageLink: "https://theblueprint.ru/upload/6468/9b30b445d128d9918da4b3ad5085881b_small.jpg",
                                      previewImageLink: "https://hvylya.net/wp-content/uploads/2017/04/Apple-640x394.jpg",
                                      placeholderColor: #colorLiteral(red: 0.07493124157, green: 0.139801532, blue: 0.2554385662, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes)],
                     tags: []),
    ShopCategoryData(categoryName: "Food",
                     shops: [ShopData(name: "KFC",
                                      description: "Menu: chicken dishes, french fries, salads, snacks, etc.",
                                      shortDescription: "Two for one price",
                                      websiteLink: "https://www.kfc.ru",
                                      imageLink: "https://kenh14cdn.com/2017/2-nhat-ban-kfc-5-1512005597643.jpg",
                                      previewImageLink: "https://shopandmall.ru/photo/your-sales-funnel-what-you-can-and-cant-control_kfc_mr7zU2-768x512.jpg",
                                      placeholderColor: #colorLiteral(red: 0.6545341015, green: 0.1229880676, blue: 0.1732276082, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "McDonald's",
                                      description: "Most popular and common fast food chain in The USA and Canada",
                                      shortDescription: "New menu",
                                      websiteLink: "https://mcdonalds.ru",
                                      imageLink: "http://reztaurante.com/uploads/mcdonald1.jpg",
                                      previewImageLink: "https://gearshunt.com/wp-content/uploads/2018/05/mcDonalds-Qs-e1526363465476.jpg",
                                      placeholderColor: #colorLiteral(red: 0.9977615476, green: 0.7533308864, blue: 0.01199052483, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Yakitoria",
                                      description: "Real Japanese and European cuisine with home delivery in Moscow!",
                                      shortDescription: "Save your 10%",
                                      websiteLink: "https://yakitoriya.ru",
                                      imageLink: "https://cdn5.pokupon.ua/uploaded/merchant_page_images/70370/data/large1200/23334055_1486303894779087_9040458936558208698_o.jpg",
                                      previewImageLink: "http://center-media.com/upload/iblock/e4e/e4eda5dca8a01d343b7eea6a930b9524.jpg",
                                      placeholderColor: #colorLiteral(red: 0.9265739322, green: 0.1133742854, blue: 0.2094681561, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Papa Johns",
                                      description: "Pizzas, snacks, salads, desserts, drinks.",
                                      shortDescription: "New pizza",
                                      websiteLink: "https://www.papajohns.ru",
                                      imageLink: "https://www.miamitodaynews.com/wp-content/uploads/2018/09/wine-and-slice.jpg",
                                      previewImageLink: "https://fastly.4sqi.net/img/general/600x600/187649156_hflV0o2jNXzHrIKCqm_Ddq25hk0A0taUmA27ePvpv0I.jpg",
                                      placeholderColor: #colorLiteral(red: 0.01218329836, green: 0.5515415668, blue: 0.4193345606, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Burger King",
                                      description: "Burgers, snacks, salads, side dishes and desserts.",
                                      shortDescription: "Two for one price",
                                      websiteLink: "https://burgerking.ru",
                                      imageLink: "https://echoboomer.pt/wp-content/uploads/2019/10/burger-king-torres-novas.jpg",
                                      previewImageLink: "https://bdn-data.s3.amazonaws.com/uploads/2018/07/23312001_H22686902-600x400.jpg",
                                      placeholderColor: #colorLiteral(red: 0.006101547275, green: 0.0716901049, blue: 0.4215092659, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes)],
                     tags: []),
    ShopCategoryData(categoryName: "Clothes",
                     shops: [ShopData(name: "Lamoda",
                                      description: "Catalog of women's, men's and children's clothing, shoes and accessories.",
                                      shortDescription: "New arrival",
                                      websiteLink: "https://www.lamoda.ru",
                                      imageLink: "https://cashback2you.ru/wp-content/uploads/2019/10/15-1.jpg",
                                      previewImageLink: "https://youtube-lessons.ru/wp-content/auploads/799905/lamoda_internet-magazin.jpg",
                                      placeholderColor: #colorLiteral(red: 0.9977995753, green: 0.6786238551, blue: 0.7828680277, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Brandshop",
                                      description: "Sale of clothes, shoes and accessories Stone Island, New Balance, Barbour, Hackett, Maison Kitsune and other brands.",
                                      shortDescription: "Save your 30%",
                                      websiteLink: "https://brandshop.ru",
                                      imageLink: "https://foxtime.ru/upload/news/a4/93/a4939bf5a55d087a51c6d376ce296af8.jpg",
                                      previewImageLink: "https://brandshop.ru/image/cache/data/news-brandshop-novyj-logotip/mini-brandshop-novyj-logotip-532x326a.jpg",
                                      placeholderColor: #colorLiteral(red: 0.5764058232, green: 0.5765079856, blue: 0.5763992667, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Kiabi",
                                      description: "French brand of fashion for the whole family at low prices - Shop Online!",
                                      shortDescription: "Your have personal coupon",
                                      websiteLink: "https://www.kiabi.ru",
                                      imageLink: "https://e-logistyka.pl/wp-content/uploads/2018/10/sklepKiabi_Brazylia.jpg",
                                      previewImageLink: "https://webevolution.ru/media/6998/dop-kart_logotipi-kiabi.jpg?mode=pad&width=696&quality=100",
                                      placeholderColor: #colorLiteral(red: 0.005735223647, green: 0, blue: 0.2101224959, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "WildBerries",
                                      description: "Collections of women's, men's and children's clothes, shoes, as well as goods for home and sports.",
                                      shortDescription: "Save your 10%",
                                      websiteLink: "https://www.wildberries.ru",
                                      imageLink: "https://static.tildacdn.com/tild3531-3563-4536-b561-613162356235/D09BD0BED0B3D0BED182.jpeg",
                                      previewImageLink: "https://apkvision.com/wp-content/uploads/2018/10/Dv-SqgjuPdMWGTCf3c9VZB0fim5gqGx_KPi9nPUmuUqzZeQ4MJ4gfsaB0j-TCShzhPgw512.png",
                                      placeholderColor: #colorLiteral(red: 0.7378610969, green: 0.2252326906, blue: 0.5863844156, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes)],
                     tags: []),
    ShopCategoryData(categoryName: "Cosmetics",
                     shops: [ShopData(name: "Pudra",
                                      description: "Sale of perfumes, decorative cosmetics, skin and hair care products.",
                                      shortDescription: "Your have personal coupon",
                                      websiteLink: "https://pudra.ru",
                                    imageLink: "https://avatars.mds.yandex.net/get-zen_doc/62191/pub_5c5c5af114574e00b1300376_5c5c5b3a70586600ad39a42c/scale_1200",
                                    previewImageLink: "https://promokodich.ru/wp-content/uploads/2015/10/pudra-promo.jpeg",
                                    placeholderColor: #colorLiteral(red: 0.9281816483, green: 0.7574380636, blue: 0.8091133237, alpha: 1),
                                    image: nil,
                                    previewImage: nil,
                                    isFavorite: false,
                                    promocodes: promocodes),
                             ShopData(name: "L'Etoile",
                                      description: "Catalog of perfumes, decorative cosmetics, hair care products, face, body, etc.",
                                      shortDescription: "Save your 30%",
                                      websiteLink: "https://www.letu.ru",
                                      imageLink: "https://avatars.mds.yandex.net/get-zen_doc/195350/pub_5bdad767228e4f00aaa60d0b_5bdad8655d390d00a97608f3/scale_1200",
                                      previewImageLink: "https://shopandmall.ru/photo/_Letual_640h480.jpg",
                                      placeholderColor: #colorLiteral(red: 0.0472619012, green: 0.1629578173, blue: 0.4771181941, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Makeup market",
                                      description: "Online store of care, decorative, professional cosmetics and perfumes Makeup market.",
                                      shortDescription: "Save your 10%",
                                      websiteLink: "https://makeupmarket.ru",
                                      imageLink: "http://promovisor.com/wp-content/uploads/2017/08/mejk-ap-market-kupon.jpg",
                                      previewImageLink: "https://makeupmarket.ru/wa-data/public/site/themes/emarket/img/settings/logo/logo.png?v5.0.1.10",
                                      placeholderColor: #colorLiteral(red: 0.9998916984, green: 1, blue: 0.9998806119, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes),
                             ShopData(name: "Gracy",
                                      description: "Sale of decorative cosmetics, face and body care products, perfumes, etc.",
                                      shortDescription: "New arrival",
                                      websiteLink: "https://gracy.ru",
                                      imageLink: "https://www.nsk-dek.ru/uploads/posts/02/3deb5285c82b6f68259f720800da6a23.jpg",
                                      previewImageLink: "https://d353r0i7qv3gvw.cloudfront.net/49/3953649/stage-mobile/6421156.jpg",
                                      placeholderColor: #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1),
                                      image: nil,
                                      previewImage: nil,
                                      isFavorite: false,
                                      promocodes: promocodes)],
                     tags: [])
]
